-- Create the table for course enrollments
create table public.enrollments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  full_name text not null,
  email text not null,
  path_preference text not null check (path_preference in ('undecided', 'ai', 'cyber')),
  status text default 'new'
);

-- Enable Row Level Security (RLS)
alter table public.enrollments enable row level security;

-- Create policy to allow anyone (anon) to insert data
create policy "Enable insert for everyone" 
on public.enrollments for insert 
to anon 
with check (true);

-- Create policy to allow only authenticated users (admins) to select data
create policy "Enable select for authenticated users only" 
on public.enrollments for select 
to authenticated 
using (true);
